easy_admin:
    site_name: '<img class="img-fluid" src="assets/img/logo-transparent.png" alt="logo">'
    # user:
    #     display_name: true
    #     display_avatar: true
    #     name_property_path: 'fullName'
    # design:
        # form_theme: # Ambos temas son necesarios para la integración de ckeditor
            # - "@EasyAdmin/form/bootstrap_4.html.twig"
            # - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        # assets:
            # css:
                # - '/css/felix.css'
    list:
        actions:
            - { name: 'show', icon: 'search', label: false }
            - { name: 'edit', icon: 'fa fa-edit', label: false }
            - { name: 'delete', icon: 'ban', label: false }
        max_results: 15
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
    show:
        max_results: 10
        